source 'https://github.com/ietstudio/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

target 'AdvertiseAdmob_Example' do
  platform :ios, '8.0'
  pod 'AdvertiseAdmob', :path => '../'
  pod 'AdvertiseAdmob/AdapterChartBoost', :path => '../'
  pod 'AdvertiseAdmob/AdapterVungle', :path => '../'
  pod 'AdvertiseAdmob/AdapterAppLovin', :path => '../'
  pod 'AdvertiseAdmob/AdapterFacebook', :path=> '../'
end
